//For hiding the entrance and degree entry//
$(document).ready(function(){
$("#button").click(function(){
$("#hid").hide();
$("#hid1").hide();
$("#hid2").hide();
$("#hid3").hide();
});
$("#button1").click(function(){
$("#hid").hide();
$("#hid1").hide();
$("#hid2").hide();
$("#hid3").hide();
});
});
$(document).ready(function(){
$("#show").click(function(){
$("#hid").show();
$("#hid1").show();
$("#hid2").show();
$("#hid3").show();
});
$("#show1").click(function(){
$("#hid").show();
$("#hid1").show();
$("#hid2").show();
$("#hid3").show();
});
});